name: build

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Output roughly what version on merge will look like
        id: versioner
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: "MAJOR:major,MINOR:minor,PATCH:patch"
          dry_run: true
